CREATE TABLE IF NOT EXISTS devices (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    business_id BIGINT UNSIGNED NULL,
    device_uuid CHAR(36) NOT NULL UNIQUE,
    device_name VARCHAR(150) NOT NULL,
    platform VARCHAR(50) NOT NULL DEFAULT 'android-tv',
    app_version VARCHAR(50) NOT NULL,
    firmware_version VARCHAR(100) NULL,
    pairing_code VARCHAR(12) NULL,
    pairing_code_expires_at DATETIME NULL,
    device_token_hash VARCHAR(255) NULL,
    status ENUM('pending_pairing', 'active', 'inactive', 'revoked') NOT NULL DEFAULT 'pending_pairing',
    last_seen_at DATETIME NULL,
    last_sync_at DATETIME NULL,
    last_sync_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    storage_free_bytes BIGINT NULL,
    screen_resolution VARCHAR(50) NULL,
    timezone VARCHAR(64) NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_devices_business_status (business_id, status),
    INDEX idx_devices_pairing_code (pairing_code),
    CONSTRAINT fk_devices_business FOREIGN KEY (business_id) REFERENCES businesses(id)
);
