CREATE TABLE IF NOT EXISTS media (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    business_id BIGINT UNSIGNED NOT NULL,
    title VARCHAR(180) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    description TEXT NULL,
    media_type ENUM('image', 'video') NOT NULL,
    mime_type VARCHAR(120) NOT NULL,
    file_size_bytes BIGINT NOT NULL,
    duration_seconds INT NULL,
    width INT NULL,
    height INT NULL,
    checksum_sha256 CHAR(64) NOT NULL,
    storage_provider VARCHAR(50) NOT NULL,
    storage_key VARCHAR(255) NOT NULL,
    storage_url TEXT NOT NULL,
    thumbnail_url TEXT NULL,
    status ENUM('processing', 'ready', 'failed', 'deleted') NOT NULL DEFAULT 'processing',
    created_by BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted_at DATETIME NULL,
    INDEX idx_media_business_deleted (business_id, deleted_at),
    INDEX idx_media_business_type_status (business_id, media_type, status),
    INDEX idx_media_original_filename (original_filename),
    CONSTRAINT fk_media_business FOREIGN KEY (business_id) REFERENCES businesses(id),
    CONSTRAINT fk_media_user FOREIGN KEY (created_by) REFERENCES users(id)
);
